@echo off
rem Launches the Loványa dev server using the bundled portable Node, so it
rem works even when node isn't on the system PATH. Generated by Claude.
set "NODE_DIR=C:\Users\SpecialXz\Documents\Claude bestie API\.nodedist\node-v24.16.0-win-x64"
set "PATH=%NODE_DIR%;%PATH%"
cd /d "C:\Users\SpecialXz\Documents\Claude bestie API\lovanya"
"%NODE_DIR%\npm.cmd" run dev
