"""QLoRA fine-tune of the judge on the gold set (TRAINING.md step 3).

Single process, single GPU: loads the configured judge 4-bit (NF4), runs
perceive() on each gold image so training prompts match the runtime judge
prompt exactly, then trains a small LoRA on (image + judge prompt) -> gold
judgment JSON. Saves the adapter to pipeline/adapters/<timestamp>/.

Run from the repo root:
    python pipeline/scripts/train_qlora.py [--epochs 3] [--lr 1e-4]

Use the result by setting LOVANYA_ADAPTER=pipeline/adapters/<timestamp>
before starting either server. 30 examples is a voice/format alignment pass,
not perception learning — rerun as data/ratings.jsonl corrections accumulate.
"""

import argparse
import json
import sys
import time
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent.parent))

import torch  # noqa: E402

from pipeline import config  # noqa: E402
from pipeline.app.qwen_analyzer import JUDGE_PROMPT_TEMPLATE, QwenAnalyzer  # noqa: E402

PIPELINE_DIR = Path(__file__).resolve().parent.parent


def build_examples(analyzer):
    """gold.jsonl -> (image_path, judge_prompt, target_json) triples,
    with perception generated by the current model so the training prompt
    is byte-compatible with what the runtime judge sees."""
    framework = Path(config.FRAMEWORK_PATH).read_text(encoding="utf-8")
    examples = []
    gold_path = PIPELINE_DIR / "data" / "gold.jsonl"
    for line in gold_path.read_text(encoding="utf-8").splitlines():
        rec = json.loads(line)
        image_path = str(PIPELINE_DIR / rec["image"])
        perception = analyzer.perceive(image_path)
        prompt = JUDGE_PROMPT_TEMPLATE.format(
            occasion=rec["occasion"],
            framework=framework,
            perception=json.dumps(perception, ensure_ascii=False),
        )
        target = json.dumps(
            {
                "scores": rec["scores"],
                "overall": rec["overall"],
                "feedback": rec["feedback"],
                "one_fix": rec["one_fix"],
            },
            ensure_ascii=False,
        )
        examples.append((image_path, prompt, target))
        print(f"  perceived {rec['image']}")
    return examples


def encode(processor, image_path, prompt, target):
    """Tokenize prompt+target; labels mask the prompt (loss on target only)."""
    from qwen_vl_utils import process_vision_info

    messages = [
        {
            "role": "user",
            "content": [
                {"type": "image", "image": image_path},
                {"type": "text", "text": prompt},
            ],
        }
    ]
    prompt_text = processor.apply_chat_template(
        messages, tokenize=False, add_generation_prompt=True
    )
    full_text = prompt_text + target + processor.tokenizer.eos_token
    image_inputs, _ = process_vision_info(messages)

    prompt_ids = processor(
        text=[prompt_text], images=image_inputs, return_tensors="pt"
    ).input_ids[0]
    inputs = processor(text=[full_text], images=image_inputs, return_tensors="pt")
    labels = inputs.input_ids.clone()
    labels[0, : len(prompt_ids)] = -100
    inputs["labels"] = labels
    return inputs


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--epochs", type=int, default=3)
    parser.add_argument("--lr", type=float, default=1e-4)
    parser.add_argument("--grad-accum", type=int, default=4)
    parser.add_argument("--rank", type=int, default=8)
    args = parser.parse_args()

    assert torch.cuda.is_available(), "QLoRA training needs the GPU"

    from peft import LoraConfig, get_peft_model, prepare_model_for_kbit_training

    print("Loading judge 4-bit…")
    analyzer = QwenAnalyzer()
    model, processor = analyzer.model, analyzer.processor

    print("Building dataset from data/gold.jsonl…")
    examples = build_examples(analyzer)
    print(f"{len(examples)} training examples")

    model = prepare_model_for_kbit_training(model)
    model.gradient_checkpointing_enable()
    lora = LoraConfig(
        r=args.rank,
        lora_alpha=args.rank * 2,
        lora_dropout=0.05,
        bias="none",
        task_type="CAUSAL_LM",
        target_modules=["q_proj", "v_proj"],
    )
    model = get_peft_model(model, lora)
    model.print_trainable_parameters()
    model.train()

    opt = torch.optim.AdamW(
        (p for p in model.parameters() if p.requires_grad), lr=args.lr
    )

    step = 0
    for epoch in range(args.epochs):
        epoch_loss, n = 0.0, 0
        for i, (image_path, prompt, target) in enumerate(examples):
            inputs = encode(processor, image_path, prompt, target).to(model.device)
            out = model(**inputs)
            loss = out.loss / args.grad_accum
            loss.backward()
            epoch_loss += out.loss.item()
            n += 1
            if (i + 1) % args.grad_accum == 0:
                torch.nn.utils.clip_grad_norm_(
                    (p for p in model.parameters() if p.requires_grad), 1.0
                )
                opt.step()
                opt.zero_grad()
                step += 1
                print(
                    f"epoch {epoch + 1}/{args.epochs} step {step} "
                    f"loss {out.loss.item():.3f} "
                    f"vram {torch.cuda.memory_allocated() / 1e9:.1f}GB"
                )
        print(f"epoch {epoch + 1} mean loss {epoch_loss / max(n, 1):.3f}")

    out_dir = PIPELINE_DIR / "adapters" / time.strftime("%Y%m%d-%H%M")
    out_dir.mkdir(parents=True, exist_ok=True)
    model.save_pretrained(str(out_dir))
    print(f"ADAPTER SAVED: {out_dir}")


if __name__ == "__main__":
    main()
